[theme]
primaryColor = "#4da6ff"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e0e0"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
headless = true
port = 8501

[global]
developmentMode = false

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[deprecation]
showfileUploaderEncoding = false
